site_name: UX_caretaker
site_url:


nav:
    - Ethnographic research: index.md
    - Stakeholder analysis: stakeholders.md
    - Personas: personas.md

site_author: Trenchi, Alessandra - Grieco, Giusy - Casado, Juan Pablo
site_description: documentation for the UX project


repo_name: UX_caretaker
repo_url: https://github.com/teragramgius/UX_caretaker

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: orange

  markdown_extensions:
    - pymdownx.highlight:
      anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - md_in_html




extra:
  version:
    provider: mike



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
